### ISSUE TITLE
Long options with =

### ISSUE THREAD

**Issue by vgarvardt** [voxelbrain/goptions#11]
Long options with values after `=` does not seems to be working:

```sh
$ go run main.go --env=dev
Error: Invalid trailing arguments: [--env=dev]
Usage: main [global options] 

Global options:
        -e, --env     Application environment, defines config section (default: prod)
        -r, --rebuild Rebuild index only, do not start web server
        -h, --help    Show this help


exit status 1
```

W/out equal sign works fine.

```sh
$ go run main.go --env dev
[LOG] 2014/12/23 - 04:11:39 | Loading config with env set to dev
```

**Comment by surma** [comment]
Sorry for taking so lang to answer, but you know... holidays ;)

This is working as intended, it even says so in the [documentation](http://godoc.org/github.com/voxelbrain/goptions):

> Short flags can be combined (e.g. `-nfv`). Long flags take their value after a separating space. The equals notation (`--long-flag=value`) is NOT supported right now.

I am still unsure if I want to support both notations. If you feel you can make a good case for it, please post it here so I can consider it for v3 which I'm (theoretically) working on :D
