### ISSUE TITLE
Any way to handle none-option parameters?

### ISSUE THREAD

**Issue by suntong** [voxelbrain/goptions#15]
Does `goptions` support handling none-option parameters?

For e.g., `rsync` takes an awful lot of options, but besides them, at the end of command line, there needs to be source and option destination. Can `goptions` handle cases like this?

Thanks

**Comment by surma** [comment]
Yup, see the [Remainder type (with example)](https://godoc.org/github.com/voxelbrain/goptions#Remainder).
