### ISSUE TITLE
Type os.File option problem on output to "-", and setting default value issues

### ISSUE THREAD

**Issue by suntong** [voxelbrain/goptions#16]
I think I've found a Type os.File option bug when output to "-", 

The https://godoc.org/github.com/voxelbrain/goptions says, 

> Type: *os.File   The given string is interpreted as a path to a file. If the string is "-"
    os.Stdin or os.Stdout will be used. os.Stdin will be returned, if the
    `rdonly` flag was set. os.Stdout will be returned, if `wronly` was set.

However, when I try it, I think it is not writing to Stdout. This is my parameter:

		Fo      *os.File `goptions:"-o, --output, description='The output', wronly"`

The whole program is available at
https://github.com/suntong/lang/blob/master/lang/Go/src/sys/CommandLineGoptionsBug.go

Here is how I prove there is a problem:

    $ go run CommandLineGoptionsBug.go execute -c test -o - 
    Selected verb: execute
    Execute.Command: test
     with verbosity: 0
    To output, Check str: ''
    To os.Stdout, Check str: ''

Note the two "Check str" output line. Now, 

    $ go run CommandLineGoptionsBug.go execute -c test -o - > /dev/null 
    To output, Check str: ''

The print out to os.Stdout is redirected, while the output of "-o -" is not. This is the problem, and I found that it is not redirecting to stderr either:

    $ go run CommandLineGoptionsBug.go execute -c test -o - > /dev/null 2>&1
    To output, Check str: ''

Still there, even stderr is redirected. 

Also, I wasn't able to give `options.Execute.Check` a default value -- When I enable line 36, 
https://github.com/suntong/lang/blob/master/lang/Go/src/sys/CommandLineGoptionsBug.go#L36
I got `invalid field name Execute.Check in struct initializer` error. 

Please help. 
Thanks

**Comment by suntong** [comment]
Just realized the my line 36's format is wrong, so I changed it to:

    var options = Options{ // Default values goes here
	    Timeout: 10 * time.Second,
	    Execute{
		    Check: "something",
	    },
    }

But got the following error:

    ./CommandLineGoptionsBug.go:36: mixture of field:value and value initializers
    ./CommandLineGoptionsBug.go:36: undefined: Execute

**Comment by surma** [comment]
Thanks for the report. My checks were off, fixed on master :)

Regarding your second issue: That’s not how type literals work. I suggest you move `Execute` to its own type á la

```Go
type Execute struct {
	// ...
}

type Options struct {
	// ...
	goptions.Verbs
	Execute `goptions:"execute"` // Embedding!
	Delete  struct {
		Path  string `goptions:"-n, --name, obligatory, description='Name of the entity to be deleted'"`
		Force bool   `goptions:"-f, --force, description='Force removal'"`
	} `goptions:"delete"`
}

var options = Options{ // Default values goes here
	Timeout: 10 * time.Second,
	Execute: Execute{
		Command: "something",
	},
}
```

**Comment by suntong** [comment]
Thanks surma. That IS quick. and thanks answering my default value question as well.
