### ISSUE TITLE
Wish item: Help description and footer

### ISSUE THREAD

**Issue by suntong** [voxelbrain/goptions#17]
Hi Surma, the more I use `goptions`, the more I like it. So I'm writing down my thought that will help to get it better. I.e., 

The thing I'm missing from `goptions` is a program description entry, which briefly describes what the program is for, and a footer, for something to mention after listing all the options. 

Most of the programs have them. I.e., the help output of `rsync` is a good example. 

Thanks

**Comment by suntong** [comment]
Oh, if there is a way to customize the "usage line", that'd be better. I.e., the line that says, 

    Usage: myprog [global options] <verb> [verb options]

**Comment by surma** [comment]
You can customize the help output, but you will need to specify a [`FlagSet`](https://godoc.org/github.com/voxelbrain/goptions#FlagSet), and not use the convenience function.

By default, the [`DefaultHelpFunc`](https://godoc.org/github.com/voxelbrain/goptions#DefaultHelpFunc) is being used to print the help (see [implementation](https://github.com/voxelbrain/goptions/blob/master/helpfunc.go#L68)). But you can write your own :)
