### ISSUE TITLE
Wish item: Use environment variables to specify options

### ISSUE THREAD

**Issue by suntong** [voxelbrain/goptions#18]
Hi Surma, once again along the line of writing down my thought that will help to get `goptions` better, (since I knew you are contemplating a new `goptions` version)...

Before using `goptions`, I use my own home-made solution, which gives me (beside the program description, usage line customization and the help footer), the ability to use environment variables to specify options. 

Please refers to [Showcasing the power of easygen with ffcvt](https://sfxpt.wordpress.com/2015/08/02/showcasing-the-power-of-easygen-with-ffcvt/) if you like to see a concrete example. 

Thanks

**Comment by surma** [comment]
I’d do that the other way around and just initialize a flag’s default value with `os.GetEnv()`. 

You could also specify another function like `GetEnvWithDefault(EnvName, defaultValue)`.

I’ll definitely not add support for env variables directly as it is a niche use-case and cause more syntactical bloat than benefit.
