### ISSUE TITLE
Positional remainder options?

### ISSUE THREAD

**Issue by wrouesnel** [voxelbrain/goptions#19]
It doesn't look currently possible to define verb-like flags which take a variable.

i.e. something like
```
myprog [global options] <template> <data>
```

Could this be supported in a similar way to verbs, by allowing a non-dashed flag name to represent a positional argument for the current verb?

**Comment by surma** [comment]
I am not sure if this is what you are looking for:

```go
package main

import (
        "log"

        "github.com/voxelbrain/goptions"
)

var options = struct {
        Verb goptions.Verbs
        VerbA struct {
                goptions.Remainder
        } `goptions:"verba"`
        VerbB struct {
                goptions.Remainder
        } `goptions:"verbb"`
}{}

func main() {
        goptions.ParseAndFail(&options)

        switch options.Verb {
        case "verba":
                log.Printf("VerbA Remainder: %s", options.VerbA.Remainder)
        case "verbb":
                log.Printf("VerbB Remainder: %s", options.VerbB.Remainder)
        }
}
```

```
surma@ws ~/s/s/goptions ❯❯❯ go run bla.go verba a b c
2016/02/20 16:55:43 VerbA Remainder: [a b c]
surma@ws ~/s/s/goptions ❯❯❯ go run bla.go verbb a b c
2016/02/20 16:55:47 VerbB Remainder: [a b c]
```

**Comment by wrouesnel** [comment]
The best way I can explain is how the Python argparse module works:
```python
#!/usr/bin/env python
import argparse
parser = argparse.ArgumentParser(description="Example program")
parser.add_argument("--flagoption", dest="flagoption", help="This is a flag option")
parser.add_argument(dest="positional_option_1", metavar="OPT1", type=int, help="Positional option 1")
parser.add_argument(dest="positional_option_2", metavar="OPT2", help="Positional option 2")
args = parser.parse_args()
```
which yields behavior like:
```
$ python test.py 
usage: test.py [-h] [--flagoption FLAGOPTION] OPT1 OPT2
```

Transposed to goptions, I'd like to be able to achieve something similar - where a positional argument is free input but the help text explains what it is.

Based on how goptions works, something like this might be possible by introducing a `goptions.Positional` marker into the struct syntax?
```go
var options = struct {
        FlagOption bool `goptions:"--flag-option, description='This is a flag option'"`
        Positional goptions.Positional
        Option1    int `goptions:"OPT1, description='Positional option 1'"`
        Option2    string `goptions:"OPT2, description='Position option 2'"`
}{}
```

**Comment by surma** [comment]
Ah, I understand. No, currently there is no such syntax is supported with goptions. I don’t think I’ll augment the parser to accommodate that, as it can be done with the current setup and I don’t feel it’s common enough to warrant the effort.

The easiest way to achieve what you want right now is to use `Remainder` in the struct and augment the `HelpFunc` to show these parameters explicitly.
