### ISSUE TITLE
Using goptions variables as global variable

### ISSUE THREAD

**Issue by AntonioSun** [voxelbrain/goptions#20]
Hi Surma, 

Would there be any side-affects if I use a goptions variable as global (configuration) variable? I.e., using them for program configuration/behavior purpose, so that not to define another set of variables having the exact same purpose?

The question may seems strange. That's because I'm having an extremely strange problem using goptions variable as global (configuration) variable. Please take a look at the changes made in 

https://github.com/AntonioSun/wts/commit/7fae008223b5c37420a5e17c151c50368d694b59

```
--- a/wts-dump.go
+++ b/wts-dump.go
@@ -323,7 +323,7 @@ func treatWtsXml(w io.Writer, checkOnly bool, decoder *xml.Decoder) error {
 }
 
 func treatComment(w io.Writer, v string) {
-       if options.Dump.Cnr {
+       if cnr {
                debug("here", 1)
                v = cmtRe.ReplaceAllString(v, "[]")
        }
@@ -471,6 +471,7 @@ func minify(xs string) string {
        return re.ReplaceAllString(xs, "")
 }
 
+var cnr bool
 var cmtRe *regexp.Regexp
 var tmsRe *regexp.Regexp
 
@@ -485,10 +486,11 @@ func dumpCmd(options Options) error {
        }
        defer fileo.Close()
 
+       cnr = options.Dump.Cnr
        if options.Dump.Raw {
-               options.Dump.Cnr = true
+               cnr = true
        }
-       if options.Dump.Cnr {
+       if cnr {
                cmtRe = regexp.MustCompile(`\[#\d+]`)
                debug("here", 1)
        }
```

The only thing that I did, was to replace the global variable `options.Dump.Cnr` with global variable `cnr`.  and the `if` statement in `func treatComment` changed from not working to working. 

Any idea why this is happening? 

Here is a sample file, if you need to test it yourself. 

```
<?xml version="1.0" encoding="utf-8"?>
<WebTest Name="Test" Id="a60ebdf8-..." Owner="" Priority="0" Enabled="True" CssProjectStructure="" CssIteration="" Timeout="0" WorkItemIds="" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010" Description="" CredentialUserName="" CredentialPassword="" PreAuthenticate="True" Proxy="default" StopOnError="False" RecordedResultFile="" ResultsLocale="">
  <Items>
    <Comment CommentText="[#1]" />
    <Request Method="GET" Guid="5477c561-3508-43dc-af23-eb6b78ef8f81" Version="1.1" Url="http://my.site.com/" ThinkTime="7" Timeout="60" ParseDependentRequests="True" FollowRedirects="False" RecordResult="True" Cache="False" ResponseTimeGoal="0" Encoding="utf-8" ExpectedHttpStatusCode="0" ExpectedResponseUrl="" ReportingName="" IgnoreHttpStatusCode="False" />
    <Comment CommentText="[#7]" />
  </Items>
</WebTest>
```

To summary up, using a goptions variable as global configuration variable for program configuration/behavior purpose works, but only if not changing its values programmatically from outside voxelbrain/goptions.

Thanks

**Comment by suntong** [comment]
Same issue. 

I've provided a [concise illustration: CommandLineGoptions2.go](https://github.com/suntong/lang/blob/master/lang/Go/src/sys/CommandLineGoptions2.go). 

```
$ go run CommandLineGoptions2.go execute -c cc -o -
Selected verb: execute
Execute.Command: cc
 with verbosity: 0
To output, Check str: 'something'
To os.Stdout, Check str: 'something'
Force: true
Force: false
```

I.e., the `Force: ` value flipped somehow.

**Comment by surma** [comment]
Generally, it is fine to use an goptions struct for global variables. goptions doesn’t touch fields that are not tagged.

Both of you are shadowing the global `options` variable with a function parameter. It’s good to see that it’s not only me who this happens to :smile: 
@AntonioSun: https://github.com/AntonioSun/wts/commit/7fae008223b5c37420a5e17c151c50368d694b59#diff-2d05cf95cfa3ef8570327794b7571adcL477
@suntong: https://github.com/suntong/lang/blob/master/lang/Go/src/sys/CommandLineGoptions2.go#L76

**Comment by suntong** [comment]
OK. Shadowing a global options variable with a function parameter will not work. Thus you are closing it. 

However, is there any workarounds? If `verb`s accept parameters, it is really natural for the main to adjust those parameters according to programming logic. Just like `cp -a` will turn on a lots of other options. It is very inconvenient that this basic feature is not supported by goptions. 

So how does `goptions` do it internally? Can you expose some functions we can call, at least to twist those Boolean variable please?

**Comment by surma** [comment]
@suntong I thought you were asking me why `Force` is `false` and then `true` in your example. That is because you are shadowing the global `options` variable and therefore working on a copy inside that function. Just remove that function parameter and work on the global variable directly or use a pointer instead.

**Comment by suntong** [comment]
Ah, got you this time -- wasn't aware the problem comes from the cookie-cutter. :-) Thanks!!
