### ISSUE TITLE
os.File type of option for output

### ISSUE THREAD

**Issue by suntong** [voxelbrain/goptions#21]
I have the following in option in my file:

		Fileo *os.File `goptions:"-o, --output, description='The dump output', wronly"`

And my main begins with:

    func main() {
	goptions.ParseAndFail(&options)

Howerver, when I invoke my program with 

    my_program -o /tmp/out 

It errors out, with the following message:

    Error: open /tmp/out: no such file or directory
    Usage: ....

I think for `wronly` option, that is meant solely for output, the package should create the file instead of error out.

**Comment by surma** [comment]
As stated in the docs:

    Any combination of create, append, rdonly, wronly, rdwr,
    excl, sync, trunc and perm can be specified and correspond directly with
    the combination of the homonymous flags in the os package.

So you need to add the `create` flag :)

**Comment by suntong** [comment]
ops, silly me. thanks.

**Comment by suntong** [comment]
Hmm, didn't find it in https://godoc.org/github.com/voxelbrain/goptions, 

So, should I `or` them together like in C:

    Fileo *os.File `goptions:"-o, --output, description='The dump output', wronly|create"`

or use extra commas?

**Comment by surma** [comment]
<img width="764" alt="screenshot 2016-04-29 22 46 38" src="https://cloud.githubusercontent.com/assets/234957/14930534/876aaf66-0e5c-11e6-87bf-fdac85b765a1.png">

Admittedly, the indentation is off. And no, flags are separated by comma. So 

```
Fileo *os.File `goptions:"-o, --output, description='The dump output', wronly, create"`
```

should work.

**Comment by suntong** [comment]
Oh, I meant to look for/ask whether `or` them together like C or use commas. Thanks for the answer.
